Repository fack2/the-crowd, pull requests merged in 2019-10, with the labels that each got.

#32 file structure related #33
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  package.json
  server/app.js
  server/controllers/index.js
  server/database/db_build.js
  server/database/db_build.sql
  server/database/db_connection.js
  server/server.js
Labels: awaiting_review

#36 read me file
  README.md
Labels: awaiting_review

#37 edit tables
  client/package.json
  package.json
  server/database/db_build.sql
Labels: awaiting_review

#41 edit some columns in database and insert data to it relate #40
  server/database/data_build.sql
  server/database/db_build.js
  server/database/db_build.sql
Labels: Done

#42 eslint and travis configurations are added
  .eslintignore
  .eslintrc.json
  .travis.yaml
  client/package-lock.json
  package-lock.json
  package.json
  server/database/db_build.js
  server/database/db_connection.js
Labels: Done

#38 display data of landing page
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/LandingPage/index.css
  client/src/components/LandingPage/index.js
Labels: awaiting_review

#39 adding responsive fixed position footer
  LICENSE
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/components/Footer/index.css
  client/src/components/Footer/index.jsx
  client/src/index.css
  client/src/logo.svg
  package-lock.json
Labels: awaiting_review

#48 Back button
  client/src/components/BackButton/index.css
  client/src/components/BackButton/index.jsx
Labels: changes-requested

#49 CategoryPledges and PledgItem components
  client/package.json
  client/src/App.js
  client/src/components/CategoryPledges/index.js
  client/src/components/PledgItem/PledgeItem.js
  client/src/components/PledgItem/style.css
  package.json
  server/app.js
  server/controllers/getCategoryPledges.js
  server/controllers/index.js
  server/database/queries/getCategoryPledges.js
Labels: awaiting_review

#58 travis fix
  .travis.yaml
Labels: awaiting_review

#60 rename travis file
  .travis.yml
Labels: awaiting_review

#46 Home pledge
  .gitignore
  client/src/App.js
  client/src/components/HomePage/index.js
  client/src/components/HomePage/style.css
  client/src/components/UserPledges/index.js
  client/src/components/UserPledges/style.css
  server/app.js
  server/controllers/index.js
  server/controllers/userPledges.js
  server/database/db_build.sql
  server/database/queries/getUserPledges.js
Labels: changes-requested

#67 Confirm congrate
  client/build/asset-manifest.json
  client/build/favicon.ico
  client/build/index.html
  client/build/precache-manifest.01a134b6f0d77718540398f6f973dc3d.js
  client/build/service-worker.js
  client/build/static/css/main.39094ddc.chunk.css
  client/build/static/css/main.39094ddc.chunk.css.map
  client/build/static/js/2.f4d2b851.chunk.js
  client/build/static/js/2.f4d2b851.chunk.js.map
  client/build/static/js/main.d5cc3f80.chunk.js
  client/build/static/js/main.d5cc3f80.chunk.js.map
  client/build/static/js/runtime-main.985e6003.js
  client/build/static/js/runtime-main.985e6003.js.map
  client/src/App.js
  client/src/components/ConfirmPage/index.js
  client/src/components/ConfirmPage/style.css
  client/src/components/CongratulationsPage/index.js
  client/src/components/CongratulationsPage/style.css
  client/src/components/HomePage/index.js
  client/src/components/PledgItem/PledgeItem.js
  client/src/components/PledgItem/style.css
  client/src/components/PledgePage/index.js
  client/src/components/PledgePage/style.css
  client/src/components/UserPledges/index.js
  server/app.js
  server/controllers/confirmPledgeToUser.js
  server/controllers/getPledgePageInfo.js
  server/controllers/index.js
  server/database/queries/confirmUserPledge.js
  server/database/queries/getPledgeInfo.js
  server/database/queries/getPledgeInstructions.js
  server/database/queries/getPledgeProsCons.js
  server/database/queries/getPledgeReferences.js
  server/database/queries/getPledgeResources.js
Labels: changes-requested

#69 fixed BackButtonStyle
  client/src/components/BackButton/index.css
Labels: awaiting_review

#44 Category
  .gitignore
  client/src/App.js
  client/src/components/Category/index.js
  client/src/components/Category/style.css
  client/src/components/DashboardPage/index.js
  client/src/components/NumberOfPledges/index.js
  client/src/components/NumberOfPledges/style.css
  package-lock.json
  server/controllers/getAllPledges.js
  server/controllers/getCategoryInfo.js
  server/controllers/getNumberOfUserPledges.js
  server/controllers/getNumberPledgesCategory.js
  server/controllers/getPledgesInCategory.js
  server/controllers/index.js
  server/database/data_build.sql
  server/database/queries/getAllPledges.js
  server/database/queries/getCategory.js
  server/database/queries/getNumberOfUserPledges.js
  server/database/queries/getNumberPledgesCategory.js
  server/database/queries/getPledgesInCategory.js
Labels: changes-requested

#79 delete fetch user data from app.js and move to the components they need
  .gitignore
  client/src/App.js
  client/src/UserContext.js
  client/src/components/HomePage/index.js
  client/src/components/PledgePage/index.js
Labels: awaiting_review

#75 stylying for home page when there is no user pledges
  client/package-lock.json
  client/package.json
  client/src/components/HomePage/index.js
  client/src/components/HomePage/style.css
  client/src/components/LandingPage/index.js
  client/src/components/LandingPage/style.css
Labels: awaiting_review

#78 added two categories to dashboard page
  client/src/components/Category/style.css
  server/database/data_build.sql
Labels: changes-requested

#80 Category pledges data props
  client/src/components/BackButton/index.css
  client/src/components/Category/index.js
  client/src/components/CategoryPledges/index.js
  client/src/components/CategoryPledges/style.css
  client/src/components/PledgItem/style.css
Labels: awaiting_review

#68 Pledge page context api
  client/src/components/ConfirmPage/index.js
  client/src/components/PledgePage/index.js
  client/src/components/PledgePage/style.css
  client/src/index.css
  server/controllers/deletePledgeToUser.js
  server/controllers/index.js
  server/database/queries/deletePledgeToUser.js
Labels: awaiting_review

#88 change height of pledge image to px instead of %
  client/src/components/PledgItem/style.css
Labels: awaiting_review

#89 change the favicon
  client/public/favicon.ico
Labels: awaiting_review

#87 Database schema
  server/database/data_build.sql
  server/database/db_build.sql
Labels: Done

#90 naming and landing page
  client/public/index.html
  client/src/components/CategoryPledges/index.js
  client/src/components/Footer/index.jsx
  client/src/components/LandingPage/index.js
  client/src/components/LandingPage/style.css
  client/src/components/PledgItem/index.js
Labels: changes-requested

#92 Style
  client/src/components/CategoryPledges/index.js
  client/src/components/CategoryPledges/style.css
  client/src/components/NumberOfPledges/style.css
Labels: awaiting_review

#73 responsive information page
  client/src/App.js
  client/src/components/InformationPage/index.css
  client/src/components/InformationPage/index.js
Labels: awaiting_review

#94 pledge page small changes
  client/src/components/ConfirmPage/style.css
  client/src/components/LandingPage/style.css
  client/src/components/PledgItem/style.css
  client/src/components/PledgePage/index.js
  client/src/components/PledgePage/style.css
Labels: changes-requested

#95 Congratulations page
  client/src/App.js
  client/src/components/CongratulationsPage/index.js
  client/src/components/CongratulationsPage/style.css
Labels: awaiting_review

#96 Dashboard style
  client/src/components/NumberOfPledges/style.css
  server/database/data_build.sql
Labels: awaiting_review

#97 fix home page problem
  client/src/components/HomePage/index.js
Labels: awaiting_review

#98 changes in filter function using id instead of name
  client/src/components/Category/index.js
Labels: awaiting_review

#99 padding for back button styling
  client/src/components/BackButton/style.css
Labels: awaiting_review

#102 FrontEnd Errors handle
  client/src/App.js
  client/src/components/FrontEndError/index.js
  client/src/components/FrontEndError/style.css
Labels: awaiting_review

#104 Rename classes name and use same name in all components
  client/src/components/Category/index.js
  client/src/components/Category/style.css
  client/src/components/CategoryPledges/index.js
  client/src/components/HomePage/style.css
  client/src/components/NumberOfPledges/index.js
  client/src/components/PledgePage/index.js
  client/src/components/PledgePage/style.css
Labels: awaiting_review

#85 delete confirmation page
  client/src/App.js
  client/src/components/BackButton/index.js
  client/src/components/BackButton/style.css
  client/src/components/Category/style.css
  client/src/components/CategoryPledges/style.css
  client/src/components/DeletePledgeConfirmation/index.js
  client/src/components/DeletePledgeConfirmation/style.css
  client/src/components/Footer/index.js
  client/src/components/HomePage/index.js
  client/src/components/HomePage/style.css
  client/src/components/LandingPage/index.js
  client/src/components/PledgItem/index.js
  client/src/components/PledgItem/style.css
  client/src/components/PledgePage/index.js
  client/src/components/PledgePage/style.css
  client/src/components/UserPledges/index.js
  client/src/components/UserPledges/style.css
  server/controllers/deletePledgeToUser.js
  server/database/db_connection.js
  server/database/queries/deletePledgeToUser.js
  server/database/queries/getUserPledges.js
Labels: awaiting_review

#106 edit the style
  client/src/components/CongratulationsPage/style.css
Labels: awaiting_review

#110 User test
  client/src/components/NumberOfPledges/index.js
Labels: awaiting_review

#120 edit the style of footer
  client/src/components/Footer/style.css
Labels: awaiting_review

#123 loading in dashboard page
  client/src/components/Category/index.js
  client/src/components/DashboardPage/index.js
  client/src/components/NumberOfPledges/index.js
Labels: awaiting_review

#112 celebrating animation
  client/package-lock.json
  client/package.json
  client/src/components/CongratulationsPage/index.js
Labels: awaiting_review

#122 update delete confirmation page design
  client/src/components/BackButton/index.js
  client/src/components/DeletePledgeConfirmation/index.js
  client/src/components/DeletePledgeConfirmation/style.css
Labels: awaiting_review

#128 pledgePage loading
  client/src/components/CategoryPledges/index.js
  client/src/components/CategoryPledges/style.css
  client/src/components/PledgePage/index.js
Labels: awaiting_review

#127 loading for home page
  client/src/components/HomePage/index.js
  client/src/components/HomePage/style.css
Labels: awaiting_review

#121 put all enrollment numbers in pledges 0
  server/database/data_build.sql
Labels: awaiting_review

#131 the positoion of clipperLoading
  client/src/components/CategoryPledges/style.css
  client/src/components/DashboardPage/index.js
  client/src/components/HomePage/style.css
Labels: awaiting_review

#136 handle pledge deletetion for more than once
  client/package-lock.json
  client/src/components/DeletePledgeConfirmation/index.js
  client/src/components/DeletePledgeConfirmation/style.css
  server/controllers/deletePledgeToUser.js
  server/database/queries/deletePledgeToUser.js
Labels: awaiting_review

#117 edit landing page
  client/src/components/LandingPage/index.js
  client/src/components/LandingPage/style.css
Labels: awaiting_review

#125 edit style
  client/src/components/HomePage/index.js
  client/src/components/HomePage/style.css
  client/src/components/UserPledges/style.css
Labels: awaiting_review

#137 edited the delete message
  client/src/components/DeletePledgeConfirmation/index.js
  client/src/components/DeletePledgeConfirmation/style.css
Labels: awaiting_review, refactor

#133 Img width
  client/src/components/CategoryPledges/index.js
  client/src/components/CategoryPledges/style.css
  client/src/components/InformationPage/index.js
  client/src/components/InformationPage/style.css
  client/src/components/PledgItem/index.js
  client/src/components/PledgItem/style.css
  client/src/components/PledgePage/style.css
Labels: changes-requested

#138 Refactor confirm congrats margins
  client/src/components/ConfirmPage/style.css
  client/src/components/CongratulationsPage/style.css
Labels: awaiting_review, refactor

#143 fix bug -- refresh confirm page
  client/src/components/ConfirmPage/index.js
Labels: awaiting_review, refactor

#142 added margin bottom for pledges category page
  client/src/components/CategoryPledges/style.css
Labels: in-progress, refactor

#144 click img
  client/src/components/UserPledges/index.js
Labels: awaiting_review

#146 change color of confirm page
  client/src/components/ConfirmPage/style.css
Labels: awaiting_review

#147 congratulation page redirect to pledge info page
  client/src/components/ConfirmPage/index.js
  client/src/components/CongratulationsPage/index.js
  client/src/components/PledgePage/index.js
Labels: T4h, awaiting_review, bug, refactor

#148 solved bug from server
  client/src/components/CategoryPledges/index.js
  client/src/components/ConfirmPage/index.js
  client/src/components/DashboardPage/index.js
  client/src/components/HomePage/index.js
  client/src/components/PledgePage/index.js
Labels: awaiting_review, refactor

#151 fix bug style
  client/src/components/CongratulationsPage/style.css
Labels: T1h, awaiting_review, bug, refactor
